---
- name: Check Linux distribution (1/2)
  include_tasks: yum.yml
  when: ansible_distribution == 'Amazon' or
        ansible_distribution == 'CentOS' or
        ansible_distribution == 'Fedora' or
        ansible_distribution == 'RedHat'
- name: Check Linux distribution (2/2)
  include_tasks: apt.yml
  when: ansible_distribution == 'Debian' or
        ansible_distribution == 'Ubuntu'
