---
- name: Setup InAccel repository
  yum_repository:
    name: inaccel
    description: InAccel Packages
    baseurl: https://dl.cloudsmith.io/public/inaccel/stable/rpm/any-distro/any-version/$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: https://setup.inaccel.com/gpg
- name: Install InAccel
  yum:
    name: inaccel-fpga
  when: install|bool
